### ISSUE TITLE
Parse env vars and config on server bootstrap

### ISSUE THREAD

**Issue by jessicayuen** [envoyproxy/xds-relay#41]
Use Cobra or other tooling so that we can start up xds-relay via command line flags or config.
ex:
* `xds-relay -c bootstrap.yml`
* `xds-relay -v INFO --upstream-url example.com`

Initially support log level, upstream url, server addr and port.

**Comment by jessicayuen** [comment]
We'll also want to support supplying aggregation-rules.yml initially.

This is a suggestion:
`xds-relay --aggregation-rules aggregation-rules.yml -c server-config.yml`

**Comment by jessicayuen** [comment]
Ah I'm finding more configuration as I implement the orchestrator, so we'll probably need these for the cache too @LisaLudique! `maxEntries int, onEvicted onEvictFunc, ttl time.Duration`

**Comment by LisaLudique** [comment]
makes sense - I'm wondering if some of these like the cache-related values can live in the bootstrap config itself but not opposed to adding more flags

**Comment by jessicayuen** [comment]
I agree, I would just keep the cache configs in the `-c server-config.yml` configuration. Things like log level and server addr, port can also live in there. More commonly changed config like log level could have a separate overridable flag.

**Comment by moderation** [comment]
This is a fly by comment but interested to see the bootstrap capability. I was surprised to see you using Cobra instead of something a little more modern and light weight like https://pkg.go.dev/github.com/peterbourgon/ff/ffcli?tab=doc.  A recent project Tailscale is using this for its [CLI capability](https://github.com/tailscale/tailscale/search?q=ffcli&unscoped_q=ffcli).  `ffcli` was described by its auther @peterbourgon in this [tweet](https://twitter.com/peterbourgon/status/1166431688705970176) as
> A straightforward and globals-free alternative to spf13/cobra and alecthomas/kingpin.

There was a report on the thread of less code and a reduction of binary size by switching from Cobra to `ffcli`.

**Comment by jessicayuen** [comment]
@moderation This is pretty neat, it wasn't a project on our radar until today. Will definitely check it out, thanks for the mention.
